// Control mappings because ucd-generate names excludes control characters
// that in the NamesList.txt file have `<` and `>` on the line with the
// codepoint.
pub const CONTROL: &'static [(u32, &'static str)] = &[
    (0, "NULL"),
    (1, "START OF HEADING"),
    (2, "START OF TEXT"),
    (3, "END OF TEXT"),
    (4, "END OF TRANSMISSION"),
    (5, "ENQUIRY"),
    (6, "ACKNOWLEDGE"),
    (7, "BELL"),
    (8, "BACKSPACE"),
    (9, "CHARACTER TABULATION"),
    (10, "LINE FEED (LF)"),
    (11, "LINE TABULATION"),
    (12, "FORM FEED (FF)"),
    (13, "CARRIAGE RETURN (CR)"),
    (14, "SHIFT OUT"),
    (15, "SHIFT IN"),
    (16, "DATA LINK ESCAPE"),
    (17, "DEVICE CONTROL ONE"),
    (18, "DEVICE CONTROL TWO"),
    (19, "DEVICE CONTROL THREE"),
    (20, "DEVICE CONTROL FOUR"),
    (21, "NEGATIVE ACKNOWLEDGE"),
    (22, "SYNCHRONOUS IDLE"),
    (23, "END OF TRANSMISSION BLOCK"),
    (24, "CANCEL"),
    (25, "END OF MEDIUM"),
    (26, "SUBSTITUTE"),
    (27, "ESCAPE"),
    (28, "INFORMATION SEPARATOR FOUR"),
    (29, "INFORMATION SEPARATOR THREE"),
    (30, "INFORMATION SEPARATOR TWO"),
    (31, "INFORMATION SEPARATOR ONE"),
];
